kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ntpd
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080   # NodePort uslugi ml-api
        hostPort: 30080
        protocol: TCP
